[versions]
gradle-android = "8.6.1"
gradle-publish-maven = "0.29.0"
gradle-test-logging = "4.0.0"
gradle-shadow = "8.3.0"

spotless = "6.25.0"
ktlint = "1.3.1"

jetbrains-annotation = "24.1.0"

kotlin-core = "2.0.20"
kotlin-dokka = "1.9.20"
kotlin-coroutines = "1.9.0" # TODO use stable version

androidx-activity = "1.9.2"

compose-runtime = "1.7.2"
compose-stableMarker = "1.0.5"
compose-activity = "1.9.2"

test-assertk = "0.28.1"
test-mockk = "1.13.12"
test-robolectric = "4.13"

# Some of our tests use JUnit4 because we include an Android module.
test-junit-core = "4.13.2"
test-junit-engine = "5.10.2"

[plugins]
gradle-publish-maven = { id = "com.vanniktech.maven.publish", version.ref = "gradle-publish-maven" }
gradle-test-logging = { id = "com.adarshr.test-logger", version.ref = "gradle-test-logging" }
gradle-shadow = { id = "com.gradleup.shadow", version.ref = "gradle-shadow" }

kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin-dokka" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-core" }

spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android" }

# TODO use multiplatform-annotations, a Kotlin artifact. (not yet released)
#  https://github.com/JetBrains/java-annotations/blob/master/CHANGELOG.md#version-2500
jetbrains-annotation = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotation" }

androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }

# TODO support for Compose Multiplatform
#  https://github.com/jisungbin/ComposeInvestigator/issues/184
compose-stableMarker = { module = "com.github.skydoves:compose-stable-marker", version.ref = "compose-stableMarker" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-runtime" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-runtime" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }

test-mockk = { module = "io.mockk:mockk", version.ref = "test-mockk" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "test-robolectric" }
test-junit-core = { module = "junit:junit", version.ref = "test-junit-core" }
test-junit-enigne = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "test-junit-engine" }
test-junit-compose = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-runtime" }
test-assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "test-assertk" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }

ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" } # for Renovate
