[versions]
gradle-android = "8.1.2"
gradle-publish-maven = "0.25.3"

jetbrains-annotation = "24.0.1"

kotlin-core = "1.9.10"
kotlin-ksp = "1.9.10-1.0.13"
kotlin-kotlinpoet = "1.14.2"
kotlin-ktlint-gradle = "11.5.1"
kotlin-ktlint-source = "0.48.2"

compose-foundation = "1.5.3"

autoservice-annotation = "1.1.1"
autoservice-ksp = "1.1.0"

test-kotest = "5.7.2"
test-junit-core = "4.13.2"
test-junit-engine = "5.10.0"
test-kotlin-compilation = "1.5.0"

[plugins]
gradle-publish-maven = { id = "com.vanniktech.maven.publish", version.ref = "gradle-publish-maven" }

kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "kotlin-ktlint-gradle" }

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android" }

jetbrains-annotation = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotation" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
kotlin-compiler-embedded = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin-core" }
kotlin-kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlin-kotlinpoet" }

compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-foundation" }

autoservice-annotation = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoservice-annotation" }
autoservice-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "autoservice-ksp" }

test-kotest = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "test-kotest" }
test-junit-core = { module = "junit:junit", version.ref = "test-junit-core" }
test-junit-enigne = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "test-junit-engine" }
test-kotlin-compilation = { module = "com.github.tschuchortdev:kotlin-compile-testing", version.ref = "test-kotlin-compilation" }
