[versions]
gradle-android = "8.4.1"
gradle-publish-maven = "0.28.0"
gradle-test-logging = "4.0.0"
gradle-shadow = "8.1.1"

spotless = "6.25.0"
ktlint = "1.2.1"

jetbrains-annotation = "24.1.0"

kotlin-core = "2.0.0"
kotlin-dokka = "1.9.20"
kotlin-coroutines = "1.9.0-RC" # K2

androidx-activity = "1.8.2"

compose-runtime = "1.6.7"
compose-activity = "1.9.0"

fastlist = "0.1.0"

test-assertk = "0.28.1"
test-mockk = "1.13.11"
test-robolectric = "4.11.1"

[plugins]
gradle-publish-maven = { id = "com.vanniktech.maven.publish", version.ref = "gradle-publish-maven" }
gradle-test-logging = { id = "com.adarshr.test-logger", version.ref = "gradle-test-logging" }
gradle-shadow = { id = "com.github.johnrengelman.shadow", version.ref = "gradle-shadow" }

kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin-dokka" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-core" }

spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android" }

jetbrains-annotation = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotation" }

kotlin-gradle-core = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
kotlin-gradle-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin-core" }
kotlin-compiler-core = { module = "org.jetbrains.kotlin:kotlin-compiler", version.ref = "kotlin-core" }
kotlin-compiler-compose = { module = "org.jetbrains.kotlin:kotlin-compose-compiler-plugin", version.ref = "kotlin-core" }

androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }

compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-runtime" }
compose-animation = { module = "androidx.compose.animation:animation-core", version.ref = "compose-runtime" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-runtime" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }

fastlist = { module = "land.sungbin.fastlist:fastlist", version.ref = "fastlist" }

test-assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "test-assertk" }
test-mockk = { module = "io.mockk:mockk", version.ref = "test-mockk" }
test-junit-compose = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-runtime" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "test-robolectric" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }

ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" } # for Renovate
