[versions]
gradle-android = "8.1.4"
gradle-publish-maven = "0.25.3"

jetbrains-annotation = "24.1.0"

kotlin-core = "1.9.20"
kotlin-coroutines = "1.7.3"
kotlin-ksp = "1.9.20-1.0.14"
kotlin-kotlinpoet = "1.15.2"
kotlin-ktlint-gradle = "11.6.1"
kotlin-ktlint-source = "0.48.2"

androidx-activity = "1.8.1"

compose-core = "1.5.4"
compose-activity = "1.8.1"

autoservice-annotation = "1.1.1"
autoservice-ksp = "1.1.0"

fastlist = "0.1.0"

test-mockk = "1.13.8"
test-kotest = "5.8.0"
test-junit-core = "4.13.2"
test-junit-engine = "5.10.1"
test-robolectric = "4.11.1"
test-kotlin-compilation = "0.4.0"

test-gradle-logging = "4.0.0"

[plugins]
gradle-publish-maven = { id = "com.vanniktech.maven.publish", version.ref = "gradle-publish-maven" }

kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "kotlin-ktlint-gradle" }

test-gradle-logging = { id = "com.adarshr.test-logger", version.ref = "test-gradle-logging" }

[libraries]
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-android" }

jetbrains-annotation = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotation" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
kotlin-compiler-embedded = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin-core" }
kotlin-kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlin-kotlinpoet" }

androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }

compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-core" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-core" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose-core" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }

autoservice-annotation = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoservice-annotation" }
autoservice-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "autoservice-ksp" }

fastlist = { module = "land.sungbin.fastlist:fastlist", version.ref = "fastlist" }

test-mockk = { module = "io.mockk:mockk", version.ref = "test-mockk" }
test-kotest-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "test-kotest" }
test-kotest-assertion = { module = "io.kotest:kotest-assertions-core", version.ref = "test-kotest" }
test-junit-core = { module = "junit:junit", version.ref = "test-junit-core" }
test-junit-enigne = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "test-junit-engine" }
test-junit-compose = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-core" }
test-robolectric = { module = "org.robolectric:robolectric", version.ref = "test-robolectric" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
test-kotlin-compilation = { module = "dev.zacsweers.kctfork:core", version.ref = "test-kotlin-compilation" }
